#!/usr/bin/env python3
"""
Plan Generator Skill - Create detailed plans for multi-step tasks
"""
import sys
from pathlib import Path
from datetime import datetime
import json

def main():
    """Main entry point for plan generator skill."""
    print("📋 Plan Generator Skill")
    print("=" * 50)
    print()

    # Get vault path
    vault_path = Path('./AI_Employee_Vault')
    needs_action = vault_path / 'Needs_Action'
    plans = vault_path / 'Plans'
    logs_path = vault_path / 'Logs'

    # Parse arguments
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--task-file', type=str, default=None)
    parser.add_argument('--complexity-threshold', type=int, default=3)
    args = parser.parse_args()

    print(f"⚙️  Configuration:")
    print(f"   Complexity threshold: {args.complexity_threshold} steps")
    if args.task_file:
        print(f"   Target task: {args.task_file}")
    print()

    # Get tasks to analyze
    if args.task_file:
        task_files = [needs_action / args.task_file]
    else:
        task_files = list(needs_action.glob('*.md'))

    if not task_files:
        print("✅ No tasks found in Needs_Action")
        return 0

    print(f"🔍 Analyzing {len(task_files)} task(s)...")
    print()

    plans_created = 0

    for task_file in task_files:
        if not task_file.exists():
            print(f"⚠️  Task file not found: {task_file.name}")
            continue

        print(f"📄 Analyzing: {task_file.name}")

        # Read task content
        content = task_file.read_text(encoding='utf-8')

        # Simple complexity analysis (count checkboxes)
        checkboxes = content.count('- [ ]')
        has_dependencies = 'depend' in content.lower() or 'blocker' in content.lower()
        has_approval = 'approval' in content.lower()

        complexity_score = checkboxes
        if has_dependencies:
            complexity_score += 2
        if has_approval:
            complexity_score += 1

        print(f"   Complexity score: {complexity_score}")
        print(f"   Checkboxes: {checkboxes}")
        print(f"   Has dependencies: {has_dependencies}")
        print(f"   Requires approval: {has_approval}")

        if complexity_score >= args.complexity_threshold:
            print(f"   ✅ Complex task - creating plan")

            # Create plan file
            plan_file = plans / f'PLAN_{task_file.stem}.md'

            plan_content = f"""---
type: plan
task_id: {task_file.stem}
created: {datetime.now().isoformat()}
priority: high
status: pending
estimated_duration: TBD
requires_approval: {str(has_approval).lower()}
---

# Plan: {task_file.stem.replace('_', ' ').title()}

## Objective
[Claude Code will analyze the task and define the objective]

## Context
- Original task: /Needs_Action/{task_file.name}
- Complexity score: {complexity_score}
- Checkboxes found: {checkboxes}
- Has dependencies: {has_dependencies}
- Requires approval: {has_approval}

## Next Steps

This plan file has been created. Claude Code should now:

1. Read the original task file: {task_file.name}
2. Read Company_Handbook.md for business context
3. Read Business_Goals.md for priorities
4. Analyze the best approach
5. Fill in this plan with:
   - Detailed objective
   - Step-by-step breakdown
   - Dependencies and blockers
   - Risk assessment
   - Resource requirements
   - Success criteria
   - Approval points

## Instructions for Claude Code

Please analyze the task and create a comprehensive plan following this structure:

### Approach Analysis
- Consider multiple approaches
- Evaluate pros/cons
- Recommend best approach

### Step-by-Step Plan
- Break into phases
- List discrete steps
- Identify dependencies
- Note approval requirements
- Estimate time for each step

### Risk Assessment
- Identify potential issues
- Assign risk levels
- Define mitigation strategies

### Resource Requirements
- Technical resources
- Human resources
- Financial resources

### Success Criteria
- Define what "done" looks like
- List measurable outcomes

### Approval Points
- Identify where human approval needed
- Explain why approval required

---
*Generated by Plan Generator Skill*
*Status: Awaiting Claude Code analysis*
"""

            plan_file.write_text(plan_content, encoding='utf-8')
            plans_created += 1

            print(f"   📝 Plan created: {plan_file.name}")
            print()

        else:
            print(f"   ℹ️  Simple task - no plan needed")
            print()

    # Log activity
    log_entry = {
        'timestamp': datetime.now().isoformat(),
        'event': 'plan_generation',
        'tasks_analyzed': len(task_files),
        'plans_created': plans_created,
        'complexity_threshold': args.complexity_threshold
    }

    log_file = logs_path / f'{datetime.now().strftime("%Y-%m-%d")}_planning.json'
    logs = []
    if log_file.exists():
        logs = json.loads(log_file.read_text())
    logs.append(log_entry)
    log_file.write_text(json.dumps(logs, indent=2))

    print(f"✅ Analysis complete: {plans_created} plan(s) created")
    print(f"📝 Log saved to: {log_file.name}")
    print()
    print("💡 Next: Claude Code should analyze tasks and complete the plans")

    return 0

if __name__ == '__main__':
    sys.exit(main())
